from .base_decoding import autoregressive_generate, beam_search_generate, autoregressive_generate_mm
from .speculative_decoding import speculative_generate, speculative_generate_mm
from .codec_base_decoding import autoregressive_generate_encoder_decoder
from .codec_speculative_decoding import speculative_generate_encoder_decoder